openapi: 3.0.2
info:
  title: OpenapiSlim4 Development Testing
  description: Bringing Slim4 and Openapi together
  version: "0.1.0"
servers:
  - url: https://localhost
paths:
  /foo:
    get:
      summary: Test GET service
      description: No parameters or body, empty response
      tags:
        - Testing
      operationId: TestService
      responses:
        '501':
          description: Not implemented
          content:
            application/json:
              schema:
                type: string