GET http://localhost:8081/phpinfo.php
Accept: application/json

###

GET http://localhost:8081
Accept: application/json

###

GET http://localhost:8081/foo
Accept: application/json

###

POST http://localhost:8081/foo
Accept: application/json

{}
###
